# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/5d18f065-d1c2-4c22-a7b2-94a2222c53d5";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/520B-215D";
      fsType = "vfat";
    };
  
  fileSystems."/data" =
    lib.mkForce {
      device = "/dev/disk/by-uuid/1fcb01cf-56e0-40b8-8f2a-551e1a95f28d";
      fsType = "xfs";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/8e26b346-64d1-4c2e-8ad0-fd2791460b38"; }];
}
