# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/1c5f14b6-2b3d-48a5-acf1-6f627e8fe8c4";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/1539-CFF0";
      fsType = "vfat";
    };

  fileSystems."/data" =
    lib.mkForce {
      device = "/dev/disk/by-uuid/1fcb01cf-56e0-40b8-8f2a-551e1a95f28d";
      fsType = "xfs";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/4282f8db-d482-4c83-ac32-bf595d087aea"; }];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
