global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes
    relabel_configs:
      # fetch metrics on port 9100.
      - source_labels: [__meta_dockerswarm_node_address]
        target_label: __address__
        replacement: $1:9100
      # set hostname as instance label
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance

  - job_name: "docker"
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes
    relabel_configs:
      # fetch metrics on port 9323.
      - source_labels: [__meta_dockerswarm_node_address]
        target_label: __address__
        replacement: $1:9323
      # set hostname as instance label
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance

  - job_name: "speedtest"
    scrape_interval: 1h
    scrape_timeout: 1m
    static_configs:
      - targets: ["monitoring_speedtest:9798"]
